a=0.0003, gamma=0.99:
  batch_size: 128
  clip_range: 0.2
  ent_coef: 0.02
  gamma: 0.99
  learning_rate: 0.0003
  n_epochs: 10
  n_steps: 2048
  device: "cpu"

a=0.0001, gamma=0.99:
  batch_size: 128
  clip_range: 0.2
  ent_coef: 0.02
  gamma: 0.99
  learning_rate: 0.0001
  n_epochs: 10
  n_steps: 2048
  device: "cpu"

a=0.0002, gamma=0.99:
  batch_size: 128
  clip_range: 0.2
  ent_coef: 0.02
  gamma: 0.99
  learning_rate: 0.0002
  n_epochs: 10
  n_steps: 2048
  device: "cpu"

a=0.0004, gamma=0.99:
  batch_size: 128
  clip_range: 0.2
  ent_coef: 0.02
  gamma: 0.99
  learning_rate: 0.0004
  n_epochs: 10
  n_steps: 2048
  device: "cpu"

a=0.0005, gamma=0.99:
  batch_size: 128
  clip_range: 0.2
  ent_coef: 0.02
  gamma: 0.99
  learning_rate: 0.0005
  n_epochs: 10
  n_steps: 2048
  device: "cpu"

a=0.0003, gamma=0.99, batch_size=256:
  batch_size: 256
  clip_range: 0.2
  ent_coef: 0.02
  gamma: 0.99
  learning_rate: 0.0003
  n_epochs: 10
  n_steps: 2048
  device: "cpu"

a=0.0003, gamma=0.99, batch_size=64:
  batch_size: 64
  clip_range: 0.2
  ent_coef: 0.02
  gamma: 0.99
  learning_rate: 0.0003
  n_epochs: 10
  n_steps: 2048
  device: "cpu"


