a=0.0005, gamma=0.99:
  batch_size: 64
  clip_range: 0.2
  ent_coef: 0.02
  gamma: 0.99
  learning_rate: 0.0005
  n_epochs: 10
  n_steps: 2048
  device: "cpu"

a=0.0005, gamma=0.97:
  batch_size: 64
  clip_range: 0.2
  ent_coef: 0.02
  gamma: 0.97
  learning_rate: 0.0005
  n_epochs: 10
  n_steps: 2048
  device: "cpu"

a=0.005, gamma=0.99:
  batch_size: 64
  clip_range: 0.2
  ent_coef: 0.02
  gamma: 0.99
  learning_rate: 0.005
  n_epochs: 10
  n_steps: 2048
  device: "cpu"

a=0.005, gamma=0.97:
  batch_size: 64
  clip_range: 0.2
  ent_coef: 0.02
  gamma: 0.97
  learning_rate: 0.005
  n_epochs: 10
  n_steps: 2048
  device: "cpu"


