ppo:
  batch_size: 64
  clip_range: 0.2
  ent_coef: 0.01
  gamma: 0.99
  learning_rate: 0.0003
  n_epochs: 10
  n_steps: 2048
  device: "cpu"

ppo_fast_learner:
  batch_size: 64
  clip_range: 0.2
  ent_coef: 0.01
  gamma: 0.99
  learning_rate: 0.003
  n_epochs: 10
  n_steps: 2048
  device: "cpu"

ppo_low_gamma:
  batch_size: 64
  clip_range: 0.2
  ent_coef: 0.01
  gamma: 0.95
  learning_rate: 0.0003
  n_epochs: 10
  n_steps: 2048
  device: "cpu"

ppo_fast_learner_low_gamma:
  batch_size: 64
  clip_range: 0.2
  ent_coef: 0.01
  gamma: 0.95
  learning_rate: 0.003
  n_epochs: 10
  n_steps: 2048
  device: "cpu"