# properties (common ones at least)
P = {
        'altitude': 'atmosphere/density-altitude',
        'phi': 'attitude/phi-deg',
        'theta': 'attitude/theta-deg',
        'psi': 'attitude/psi-deg',
        'q': 'velocities/q-rad_sec',
        'p': 'velocities/p-rad_sec',
        'r': 'velocities/r-rad_sec',
        'alpha': 'aero/alpha-deg',
        'alpha_dot': 'aero/alphadot-deg_sec',
        'beta': 'aero/beta-deg',
        'beta_dot': 'aero/betadot-deg_sec',
        'airspeed': 'velocities/true-airspeed',
        'u': 'velocities/u-fps',
        'v_ms': 'velocities/v-ms',
        'v': 'velocities/v-fps',
        'w': 'velocities/w-fps',
        'aileron': 'fcs/aileron-cmd-norm',
        'elevator': 'fcs/elevator-cmd-norm',
        'rudder': 'fcs/rudder-cmd-norm',
        'throttle': 'fcs/throttle-cmd-norm',
        'time': 'sim-time-sec',
}
